apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: stateorganisationsnames
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: localhost:27017
    - name: username
      value: picshare
    - name: password
      value: MySuperPassword
    - name: databaseName
      value: picshare
    - name: collectionName
      value: organisations-name
    - name: params
      value: ?authSource=admin