apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statealbums
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: mongo:27017
    - name: username
      value: picshare
    - name: password
      value: MySuperPassword
    - name: databaseName
      value: picshare
    - name: collectionName
      value: albums
    - name: params
      value: ?authSource=admin