name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    uses: prism-be/picshare-utils/.github/workflows/ci-dotnet.yaml@main
    with:
      sonarProjectKey: prism-be_picshare-services-authentication
      sonarProjectName: picshare-services-authentication
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}